#!/bin/bash
isVGAconnected=`xrandr | grep 'VGA1 connected'`
if [ -n "$isVGAconnected" ];
then
	xrandr --output eDP1 --auto --output VGA1 --auto --left-of eDP1
	polybarlaunch
	feh --bg-fill ~/.config/wall.jpg ~/.config/wall.jpg
else
	polybarlaunch 
	feh --bg-fill ~/.config/wall.jpg
fi
