#!/bin/sh

options="laptop\nVGA"
selected=$(echo -e "$options" | dmenu -i)

case "$selected" in
	laptop)
		xrandr | grep 'VGA1 connected' && xrandr --output eDP1 --auto --output VGA1 --off --right-of eDP1
		feh --bg-fill ~/.config/wall.jpg
		;;
	VGA)
		xrandr | grep 'VGA1 connected' && xrandr --output eDP1 --auto --output VGA1 --auto --left-of eDP1
		feh --bg-fill ~/.config/wall.jpg ~/.config/wall.jpg 
		;;
esac

