#!/bin/sh
dclock() {
#i3lock version
#i3lock -c 33334d
#betterscreenlock version
betterlockscreen -l dim
}

case "$1" in
    lock)
        dclock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
	systemctl suspend && dclock
        ;;
    hibernate)
        systemctl hibernate && dclock
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
