#!/bin/sh
dclock() 
{
	i3lock -e -f -u -c 33334d
}

case "$1" in
    lock)
        dclock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
	dclock && systemctl suspend
        ;;
    hibernate)
        dclock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
